<a href="https://colab.research.google.com/github/ra-vb/python_code/blob/main/Case_study_testing_hypothesis_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np
import math
from scipy.stats import norm
data=pd.read_csv('/content/Sales_add.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


In [5]:
data.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

In [7]:
data.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [8]:
#H0 mu=x
#H1:mu>x
import scipy.stats as stats

mean_before = 149239.954545
std_before = 14844.042921
size = 22
mean_after = 231123.727273
std_after = 25556.777061
np.random.seed(0)
Sales_before_digital_add = np.random.normal(loc=mean_before, scale=std_before, size=size)
Sales_after_digital_add = np.random.normal(loc=mean_after, scale=std_after, size=size)
t_statistic, p_value = stats.ttest_rel(Sales_after_digital_add, Sales_before_digital_add,alternative='greater')
print(f'T-statistic: {t_statistic}')
print(f'P-value: {p_value}')
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. There is a significant increase in sales after digital marketing.")
else:
    print("Fail to reject the null hypothesis. There is no significant increase in sales after digital marketing.")


T-statistic: 11.160867507623982
P-value: 1.3694184071864267e-10
Reject the null hypothesis. There is a significant increase in sales after digital marketing.


In [15]:
from scipy.stats import chi2_contingency
#print(data.head())
contingency_table = pd.crosstab(data['Region'], data['Manager'])
chi2_stat, p_val, dof, expected = chi2_contingency(contingency_table)
print(f'Chi-square statistic: {chi2_stat}')
print(f'P-value: {p_val}')
print(f'Degrees of freedom: {dof}')
print('Expected frequencies table:')
print(expected)
alpha=0.05
if p_value<alpha:
  print("Reject the null hypothesis:there is any dependency between the features region and manager")
else:
  print("Fail to rejct the hypothesis: there is no dependency between the features region and manager")


Chi-square statistic: 3.050566893424036
P-value: 0.5493991051158094
Degrees of freedom: 4
Expected frequencies table:
[[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]
Reject the null hypothesis:there is any dependency between the features region and manager
